// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTqrbzxkb8nTlseYKdfJTwtm3ABV5U6bk',
    appId: '1:801935419683:web:55bc43e1887d08a9d94496',
    messagingSenderId: '801935419683',
    projectId: 'todo-69e21',
    authDomain: 'todo-69e21.firebaseapp.com',
    storageBucket: 'todo-69e21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnXOUYFNVUT8dXecpmI0m8UmTP3mE-NJg',
    appId: '1:801935419683:android:f39cca63b02d193ad94496',
    messagingSenderId: '801935419683',
    projectId: 'todo-69e21',
    storageBucket: 'todo-69e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0O6tzPhIFo3pp5i2KpfjWu53juityGng',
    appId: '1:801935419683:ios:cc8a4ff072e1060cd94496',
    messagingSenderId: '801935419683',
    projectId: 'todo-69e21',
    storageBucket: 'todo-69e21.appspot.com',
    iosBundleId: 'com.example.flutterDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTqrbzxkb8nTlseYKdfJTwtm3ABV5U6bk',
    appId: '1:801935419683:web:c1f196a796ea43fed94496',
    messagingSenderId: '801935419683',
    projectId: 'todo-69e21',
    authDomain: 'todo-69e21.firebaseapp.com',
    storageBucket: 'todo-69e21.appspot.com',
  );
}
